
from ursina import *

app = Ursina()

class Player(ursina.Entity):
    def __init__(self):
        super().__init__()
        self.model = 'cube'
        self.collider = 'box'
        self.scale_y = 2
        self.scale_x = .5
        self.scale_z = .5
        self.origin_y = -.5
        self.color = color.color(1, 0, 0)
        self.speed = 0.1
        self.rotation_speed = .05
        self.camera.enabled = True
        self.camera.parent = self
        self.camera.position = (0, 1.5, 0)
        self.camera.rotation = (0, 0, 0)
        self.camera.fov = 90
        self.camera.orthographic_size = 10
        self.camera.far_clip = 100
        self.camera.near_clip = .1
        self.camera.background_color = color.color(0, 0, 0, 0)
        self.camera.clear_color_buffer = False
        self.camera.clear_depth_buffer = False
        self.camera.projection_type = 'perspective'
        self.camera.ambient_light = color.color(1)
        self.camera.ambient_light_intensity = .1
        self.camera.directional_light_color = color.color(1)
        self.camera.directional_light_intensity = .5
        self.camera.directional_light_rotation = (45, 45, 0)
        self.camera.directional_light_enabled = True
        self.camera.fog_enabled = True
        self.camera.fog_color = color.color(0, 0, 0, 0)
        self.camera.fog_start = 0
        self.camera.fog_end = 100
        self.camera.fog_density = 0
        self.camera.fog_type = 'linear'
        self.camera.skybox_enabled = True
        self.camera.skybox_color = color.color(0, 0, 0, 0)
        self.camera.skybox_intensity = 1
        self.camera.skybox_rotation = (0, 0, 0)
        self.camera.skybox_texture = 'skybox'
        self.camera.skybox_texture_scale = 1
        self.camera.skybox_texture_offset = (0, 0)
        self.camera.skybox_texture_tiling = (1, 1)
        self.camera.skybox_texture_rotation = 0
        self.camera.skybox_texture_flip = (False, False)
        self.camera.skybox_texture_mirror = (False, False)
        self.camera.skybox_texture_wrap = (False, False)
        self.camera.skybox_texture_filter = 'linear'
        self.camera.skybox_texture_anisotropy = 1
        self.camera.skybox_texture_mipmap = True
        self.camera.skybox_texture_mip_bias = 0
        self.camera.skybox_texture_mip_min = 0
        self.camera.skybox_texture_mip_max = 1000
        self.camera.skybox_texture_mip_auto_generate = True
        self.camera.skybox_texture_mip_auto_generate_margin = 0
        self.camera.skybox_texture_mip_auto_generate_mode = 'default'
        self.camera.skybox_texture_mip_auto_generate_use_existing = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format = False
        self.camera.skybox_texture_mip_auto_generate_use_existing_if_exists_and_complete_or_is_readable_and_valid_or_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and_has_valid_format_or_is_readable_and

app.run()